'use client';

import Link from 'next/link';
import { useTranslations } from 'next-intl';
import { cleanText, relTimeShort } from './utils';
import { TeammateAvatar } from './TeammateAvatar';

export interface DeckTask {
  id: string;
  title: string;
  kind: string | null;
  priority: number | null;
  projectName: string | null;
}

export interface BoardDecisions {
  // Things gone wrong, in severity order:
  //   stuck  = verification wedged in auto_running/proof_evaluating > 24h
  //   failed = proof was rejected; owner must override or re-request
  //   drift  = AI couldn't route (status='unassigned')
  stuck: DeckTask[];
  stuckTotal: number;
  failed: DeckTask[];
  failedTotal: number;
  drift: DeckTask[];
  driftTotal: number;
}

export interface BoardUpdate {
  id: string;
  projectId: string;
  projectName: string;
  message: string;
  // `summary` is Recgon's plain-English read of the commit (1 sentence,
  // generated by the `commit_summary` LLM worker). `null` until the job
  // completes; in that interim the UI falls back to `message` and shows
  // a subtle "summarizing…" pulse.
  summary: string | null;
  summarizing: boolean;
  sha: string;
  url: string;
  committedAt: string;
  authorName: string | null;
  authorAvatar: string | null;
}

// Team-pulse subset consumed by the TEAM HEALTH column. Mirrors the
// `/api/overview/team-pulse` response shape (members + velocity + idle
// summary). See `app/api/overview/team-pulse/route.ts` for the source.
export interface BoardTeamMember {
  teammateId: string;
  displayName: string;
  avatarColor: string | null;
  avatarUrl: string | null;
  inFlight: number;
  capacityHours: number;
  loadPct: number;
  completed7d: number;
  isIdle: boolean;
}
export interface BoardTeamPulse {
  members: BoardTeamMember[];
  velocity: { thisWeek: number; lastWeek: number; delta: number; trend: 'up' | 'down' | 'flat' };
  idleCount: number;
  totalMembers: number;
}

interface Props {
  decisions: BoardDecisions;
  updates: BoardUpdate[];
  teamPulse: BoardTeamPulse | null;
  loading: boolean;
  now?: Date | null;
  variant?: 'classic' | 'refined';
}

// HomeBoard — three columns of equal weight, each answering ONE question.
// Operator's terminal aesthetic: severity ribbon up top, oversize numeric
// counter, severity-tinted dotted backplate, and items rendered as compact
// briefing rows.
export default function HomeBoard({ decisions, updates, teamPulse, loading, now = null, variant = 'classic' }: Props) {
  const t = useTranslations('home');
  const totalDecisions = decisions.stuckTotal + decisions.failedTotal + decisions.driftTotal;
  const topFailed = decisions.failed[0];
  const topStuck = decisions.stuck[0];
  const topDrift = decisions.drift[0];

  const safeUpdates = updates ?? [];
  const visibleUpdates = safeUpdates.slice(0, 4);

  // Top 3 most-loaded teammates for the TEAM HEALTH column.
  const topLoaded = (teamPulse?.members ?? [])
    .slice()
    .sort((a, b) => b.loadPct - a.loadPct)
    .slice(0, 4);

  // Tone for TEAM HEALTH derives from real signal so the column's color
  // tracks how the team is actually doing — not just the velocity trend.
  //   crit = at least one teammate is overloaded (>=100% load)
  //   warn = someone is idle, or velocity declining
  //   good = balanced + steady-or-up
  const teamTone: 'crit' | 'warn' | 'good' | 'unknown' = (() => {
    if (!teamPulse) return 'unknown';
    if (teamPulse.members.some((m) => m.loadPct >= 100)) return 'crit';
    if (teamPulse.idleCount > 0) return 'warn';
    if (teamPulse.velocity.trend === 'down') return 'warn';
    return 'good';
  })();

  // Headline number for TEAM HEALTH = average load across non-idle members.
  // This is the single best "is the team firing?" gauge — overloaded shows
  // up as >100%, slack shows up as a low number, balanced lands ~60-80%.
  const teamLoadAvg = (() => {
    if (!teamPulse) return 0;
    const active = teamPulse.members.filter((m) => !m.isIdle);
    if (active.length === 0) return 0;
    return Math.round(
      active.reduce((sum, m) => sum + m.loadPct, 0) / active.length,
    );
  })();

  return (
    <section className="v2-bd" data-variant={variant} data-has-attention={totalDecisions > 0 ? 'true' : 'false'}>
      <div className="v2-bd-grid">
        {/* ── COLUMN 1: ATTENTION ── */}
        <div className="glass-card v2-bd-col" data-tone="crit">
          <span className="v2-bd-ribbon" aria-hidden="true" />
          <div className="v2-bd-backplate" aria-hidden="true" />

          <header className="v2-bd-col-head">
            <div className="v2-bd-col-tag">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <polygon points="12 2 22 20 2 20 12 2" />
                {/* Exclamation stem (lengthened) and dot (zero-length stroke
                    rendered as a round point thanks to strokeLinecap). */}
                <line x1="12" y1="9" x2="12" y2="14" />
                <line x1="12" y1="17.5" x2="12" y2="17.5" />
              </svg>
              <span>{t('board.attention')}</span>
            </div>
            {!loading && (
              <div className="v2-bd-counter">
                <span className="v2-bd-counter-num">
                  {totalDecisions.toString().padStart(2, '0')}
                </span>
                <span className="v2-bd-counter-lab">
                  {variant === 'refined' ? t('board.needsYourCall') : t('board.thingsGoneWrong')}
                </span>
              </div>
            )}
          </header>

          {loading ? (
            <BoardColSkel />
          ) : totalDecisions === 0 ? (
            <BoardClear text={variant === 'refined' ? t('board.clearRefined') : t('board.clearClassic')} />
          ) : (
            <div className="v2-bd-stack">
              {topFailed && (
                <DecisionItem
                  href="/verify?filter=failed"
                  severity="crit"
                  count={decisions.failedTotal}
                  label={t('board.failedVerifications')}
                  topTitle={cleanText(topFailed.title)}
                  topProject={topFailed.projectName}
                />
              )}
              {topStuck && (
                <DecisionItem
                  href="/verify?filter=stuck"
                  severity="crit"
                  count={decisions.stuckTotal}
                  label={t('board.stuck24h')}
                  topTitle={cleanText(topStuck.title)}
                  topProject={topStuck.projectName}
                />
              )}
              {topDrift && (
                /* Drift = unassigned (routing problem), not a verification
                   problem — keeps the link going to the broader task list. */
                <DecisionItem
                  href="/tasks?filter=drift"
                  severity="warn"
                  count={decisions.driftTotal}
                  label={t('board.couldNotRoute')}
                  topTitle={cleanText(topDrift.title)}
                  topProject={topDrift.projectName}
                />
              )}
            </div>
          )}

          {!loading && totalDecisions > 0 && (
            <Link href="/verify" className="v2-bd-col-link" aria-label={t('board.reviewQueueAria')}>
              <span>{t('board.reviewQueue')}</span>
              {/* list/queue glyph — opens the triage queue */}
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round">
                <line x1="9" y1="6" x2="20" y2="6" />
                <line x1="9" y1="12" x2="20" y2="12" />
                <line x1="9" y1="18" x2="20" y2="18" />
                <circle cx="4.5" cy="6" r="1.2" />
                <circle cx="4.5" cy="12" r="1.2" />
                <circle cx="4.5" cy="18" r="1.2" />
              </svg>
            </Link>
          )}
        </div>

        {/* ── COLUMN 2: UPDATES — recent commits across the team's
              GitHub-connected projects. Real shipped work, not AI-derived
              "improvements". ── */}
        <div className="glass-card v2-bd-col" data-tone="info">
          <span className="v2-bd-ribbon" aria-hidden="true" />
          <div className="v2-bd-backplate" aria-hidden="true" />

          <header className="v2-bd-col-head">
            <div className="v2-bd-col-tag">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6" aria-hidden="true">
                <circle cx="12" cy="12" r="3" />
                <line x1="3" y1="12" x2="9" y2="12" />
                <line x1="15" y1="12" x2="21" y2="12" />
              </svg>
              <span>{t('board.updates')}</span>
            </div>
            {!loading && (
              <div className="v2-bd-counter">
                <span className="v2-bd-counter-num">
                  {safeUpdates.length.toString().padStart(2, '0')}
                </span>
                <span className="v2-bd-counter-lab">{t('board.recentCommits')}</span>
              </div>
            )}
          </header>

          {loading ? (
            <BoardColSkel />
          ) : visibleUpdates.length === 0 ? (
            <BoardClear text={t('board.noCommits')} />
          ) : (
            <ul className="v2-bd-updates">
              {visibleUpdates.map((u) => (
                <li key={u.id} className="v2-bd-update">
                  <a
                    href={u.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="v2-bd-update-link"
                    data-summarizing={u.summarizing ? 'true' : undefined}
                  >
                    <span className="v2-bd-update-sha" aria-hidden="true">{u.sha}</span>
                    <span className="v2-bd-update-body">
                      <span className="v2-bd-update-text">
                        {cleanText(u.summary ?? u.message)}
                      </span>
                      <span className="v2-bd-update-meta">
                        {u.summarizing && (
                          <>
                            <span className="v2-bd-update-pending" aria-hidden="true">
                              <span className="v2-bd-update-pending-dot" />
                              {t('board.recgonReading')}
                            </span>
                            <span className="v2-bd-update-sep">·</span>
                          </>
                        )}
                        <span className="v2-bd-update-project">{u.projectName}</span>
                        <span className="v2-bd-update-sep">·</span>
                        {u.authorName && (
                          <>
                            <span className="v2-bd-update-author">{u.authorName}</span>
                            <span className="v2-bd-update-sep">·</span>
                          </>
                        )}
                        <span className="v2-bd-update-time">
                          {u.committedAt ? t('board.timeAgo', { time: relTimeShort(u.committedAt, now ?? Date.now()) }) : t('board.recent')}
                        </span>
                      </span>
                    </span>
                    <span className="v2-bd-update-arrow" aria-hidden="true">↗</span>
                  </a>
                </li>
              ))}
            </ul>
          )}

          {!loading && safeUpdates.length > visibleUpdates.length && (
            <Link href="/projects" className="v2-bd-col-link" aria-label={t('board.seeAllUpdatesAria', { count: safeUpdates.length })}>
              <span>{t('board.seeAllUpdates', { count: safeUpdates.length })}</span>
              {/* git-branch glyph — represents commit / project history */}
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="6" cy="6" r="2.4" />
                <circle cx="6" cy="18" r="2.4" />
                <circle cx="18" cy="6" r="2.4" />
                <line x1="6" y1="8.4" x2="6" y2="15.6" />
                <path d="M18 8.4 a 6 6 0 0 1 -6 6 H 8.4" />
              </svg>
            </Link>
          )}
        </div>

        {/* ── COLUMN 3: TEAM HEALTH — load distribution + velocity.
              Slipping-products signal moved to PORTFOLIO (which already
              sorts by health), so this slot now answers "is the team
              firing?" instead of duplicating risk surfaces. ── */}
        <div className="glass-card v2-bd-col" data-tone={teamTone}>
          <span className="v2-bd-ribbon" aria-hidden="true" />
          <div className="v2-bd-backplate" aria-hidden="true" />

          <header className="v2-bd-col-head">
            <div className="v2-bd-col-tag">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6" aria-hidden="true">
                {/* heart-pulse glyph */}
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
              <span>{t('board.teamHealth')}</span>
            </div>
            {!loading && (
              <div className="v2-bd-counter">
                <span className="v2-bd-counter-num">
                  {teamPulse ? `${teamLoadAvg}%` : '··'}
                </span>
                <span className="v2-bd-counter-lab">{t('board.avgTeamLoad')}</span>
              </div>
            )}
          </header>

          {loading ? (
            <BoardColSkel />
          ) : !teamPulse || teamPulse.members.length === 0 ? (
            <BoardClear text={t('board.noTeammates')} />
          ) : (
            <ul className="v2-bd-loads">
              {topLoaded.map((m) => (
                <li key={m.teammateId} className="v2-bd-load">
                  <TeammateAvatar
                    name={m.displayName}
                    avatarUrl={m.avatarUrl}
                    avatarColor={m.avatarColor}
                    isIdle={m.isIdle}
                    size={22}
                  />
                  <span className="v2-bd-load-body">
                    <span className="v2-bd-load-head">
                      <span className="v2-bd-load-name">{m.displayName}</span>
                      <span className="v2-bd-load-pct" data-load={
                        m.loadPct >= 90 ? 'high' :
                        m.loadPct >= 60 ? 'med' :
                        m.loadPct === 0 ? 'idle' : 'low'
                      }>
                        {m.isIdle ? t('board.idle') : `${m.loadPct}%`}
                      </span>
                    </span>
                    <span className="v2-bd-load-bar-track" aria-hidden="true">
                      <span
                        className="v2-bd-load-bar-fill"
                        data-load={
                          m.loadPct >= 90 ? 'high' :
                          m.loadPct >= 60 ? 'med' : 'low'
                        }
                        style={{ width: `${Math.min(100, Math.max(2, m.loadPct))}%` }}
                      />
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          )}

          {!loading && teamPulse && (
            <div className="v2-bd-load-foot">
              <span className="v2-bd-load-foot-cell">
                {t('board.shipped', { count: teamPulse.velocity.thisWeek })}{' '}
                <span className="v2-bd-load-trend" data-trend={teamPulse.velocity.trend}>
                  {teamPulse.velocity.trend === 'up' ? '▲' : teamPulse.velocity.trend === 'down' ? '▼' : '·'}
                  {' '}
                  {teamPulse.velocity.delta > 0 ? '+' : ''}{teamPulse.velocity.delta}
                </span>
              </span>
              <span className="v2-bd-load-foot-cell">
                {teamPulse.idleCount > 0
                  ? t('board.someIdle', { idle: teamPulse.idleCount, total: teamPulse.totalMembers })
                  : t('board.allActive', { total: teamPulse.totalMembers })}
              </span>
            </div>
          )}

          {!loading && (
            <Link href="/team" className="v2-bd-col-link" aria-label={t('board.viewRosterAria')}>
              <span>{t('board.viewRoster')}</span>
              {/* users glyph — represents team / roster */}
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="9" cy="8" r="3.2" />
                <path d="M3 20v-1.2 a 4 4 0 0 1 4 -4 h 4 a 4 4 0 0 1 4 4 V 20" />
                <circle cx="17" cy="9" r="2.4" />
                <path d="M21 18.4 v -0.8 a 3 3 0 0 0 -2.6 -3" />
              </svg>
            </Link>
          )}
        </div>
      </div>

      <style>{stylesheet}</style>
    </section>
  );
}

function DecisionItem({
  href, severity, count, label, topTitle, topProject,
}: {
  href: string;
  severity: 'crit' | 'warn' | 'info';
  count: number;
  label: string;
  topTitle: string;
  topProject: string | null;
}) {
  return (
    <Link href={href} className="v2-bd-dec" data-sev={severity}>
      <div className="v2-bd-dec-head">
        <span className="v2-bd-dec-count">{count.toString().padStart(2, '0')}</span>
        <span className="v2-bd-dec-label">{label}</span>
        <span className="v2-bd-dec-arrow" aria-hidden="true">→</span>
      </div>
      <div className="v2-bd-dec-top">
        <span className="v2-bd-dec-text">
          {topTitle}
          {topProject && <span className="v2-bd-dec-project"> · {topProject}</span>}
        </span>
      </div>
    </Link>
  );
}

function BoardColSkel() {
  return (
    <div className="v2-bd-skel">
      <div className="v2-bd-skel-line v2-bd-skel-l" />
      <div className="v2-bd-skel-line v2-bd-skel-m" />
      <div className="v2-bd-skel-line v2-bd-skel-s" />
    </div>
  );
}

function BoardClear({ text }: { text: string }) {
  return (
    <div className="v2-bd-clear">
      <span className="v2-bd-clear-glyph" aria-hidden="true">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6">
          <polyline points="5 12 10 17 19 8" />
        </svg>
      </span>
      <span>{text}</span>
    </div>
  );
}

const stylesheet = `
  .v2-bd { display: block; }

  .v2-bd-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 14px;
    align-items: stretch;
  }
  .v2-bd[data-variant='refined'] .v2-bd-grid {
    grid-template-columns: minmax(320px, 1.18fr) minmax(260px, 0.91fr) minmax(260px, 0.91fr);
  }
  .v2-bd[data-variant='refined'][data-has-attention='false'] .v2-bd-grid {
    grid-template-columns: repeat(3, 1fr);
  }
  @media (max-width: 1024px) {
    .v2-bd-grid { grid-template-columns: 1fr; gap: 12px; }
    .v2-bd[data-variant='refined'] .v2-bd-grid { grid-template-columns: 1fr; }
  }

  /* ── Column shell — composes the .glass-card primitive (defined in
        globals.css) with cockpit-specific overrides: tighter padding,
        column flex layout, no scale-on-hover (the 3-up grid would jitter),
        and a thin tone-tinted ribbon at the top edge. The heavy per-tone
        gradient bg + dotted backplate of the previous "vibe-coded" version
        is gone — we let glass-card's signature-pink frosted gradient carry
        the look, identical to the rest of the app. ── */
  .v2-bd-col.glass-card {
    /* Override glass-card defaults that don't fit a 3-col cockpit grid. */
    padding: 20px 22px 18px;
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    gap: 16px;
    min-height: 260px;
  }
  .v2-bd[data-variant='refined'] .v2-bd-col.glass-card {
    border-radius: 10px;
    min-height: 236px;
  }
  .v2-bd[data-variant='refined'] .v2-bd-col-head {
    gap: 10px;
  }
  .v2-bd[data-variant='refined'] .v2-bd-col-tag {
    letter-spacing: 0;
    text-transform: none;
    font-size: 11px;
  }
  .v2-bd[data-variant='refined'] .v2-bd-counter-num {
    font-size: 32px;
    letter-spacing: 0;
  }
  .v2-bd[data-variant='refined'] .v2-bd-counter-lab {
    letter-spacing: 0;
  }
  .v2-bd-col.glass-card:hover {
    /* glass-card scales 1.015 by default — distracting in a 3-col grid. */
    transform: translateZ(0);
    box-shadow: var(--shadow-float), var(--edge-highlight), var(--edge-shadow);
  }

  /* Top ribbon dropped — read as decorative without informational value.
     Tone is carried by the counter + header tag color now. */
  .v2-bd-ribbon { display: none; }

  /* Backplate hidden — the glass-card gradient already provides enough
     surface texture; an additional dot field reads as visual noise. */
  .v2-bd-backplate { display: none; }

  /* HEAD — tag + counter */
  .v2-bd-col-head {
    display: flex;
    flex-direction: column;
    gap: 14px;
    padding-bottom: 12px;
    border-bottom: 1px solid rgba(var(--signature-rgb), 0.08);
  }
  .v2-bd-col-tag {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    letter-spacing: 1.4px;
    text-transform: uppercase;
    font-weight: 700;
    color: var(--txt-faint);
    width: fit-content;
  }
  .v2-bd-col[data-tone='crit'] .v2-bd-col-tag { color: var(--danger, #dc2626); }
  .v2-bd-col[data-tone='good'] .v2-bd-col-tag { color: var(--success, #059669); }
  .v2-bd-col[data-tone='warn'] .v2-bd-col-tag { color: var(--warning, #d97706); }
  .v2-bd-col[data-tone='info'] .v2-bd-col-tag { color: var(--signature); }

  .v2-bd-counter {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .v2-bd-counter-num {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 38px;
    font-weight: 700;
    line-height: 1;
    letter-spacing: -0.04em;
    color: var(--txt-pure);
    font-variant-numeric: tabular-nums;
  }
  .v2-bd-col[data-tone='crit'] .v2-bd-counter-num { color: var(--danger, #dc2626); }
  .v2-bd-col[data-tone='good'] .v2-bd-counter-num { color: var(--success, #059669); }
  .v2-bd-col[data-tone='warn'] .v2-bd-counter-num { color: var(--warning, #d97706); }
  .v2-bd-col[data-tone='info'] .v2-bd-counter-num { color: var(--signature); }

  .v2-bd-counter-lab {
    font-size: 11.5px;
    color: var(--txt-muted);
    letter-spacing: -0.005em;
    line-height: 1.3;
  }

  /* "See all" links collapse to a floating circular icon centered on
     the bottom of the card. Hidden until card hover, then it pops in.
     The label text doubles as a tooltip that appears when the icon
     itself is hovered. The card reserves bottom space so the button
     stays clear of the content above. */
  .v2-bd-col.glass-card {
    position: relative;
    padding-bottom: 56px;
  }
  .v2-bd-col-link {
    position: absolute;
    left: 50%;
    bottom: 12px;
    margin-top: 0;
    width: 30px;
    height: 30px;
    padding: 0;
    /* Liquid-glass material — same recipe as the topnav cmd-k button
       and team switcher: heavy blur + saturate, design-token substrate. */
    background: var(--glass-substrate);
    backdrop-filter: blur(40px) saturate(180%);
    -webkit-backdrop-filter: blur(40px) saturate(180%);
    border: 1px solid var(--border, var(--rule, rgba(255, 255, 255, 0.10)));
    border-radius: 50%;
    color: var(--txt, var(--txt-pure));
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0;
    opacity: 0;
    transform: translateX(-50%) translateY(4px) scale(0.85);
    pointer-events: none;
    box-shadow: var(--shadow-float, 0 6px 18px rgba(0, 0, 0, 0.28));
    transition:
      opacity 260ms cubic-bezier(0.2, 0.8, 0.2, 1),
      transform 260ms cubic-bezier(0.2, 0.8, 0.2, 1),
      background 200ms ease,
      border-color 200ms ease,
      box-shadow 200ms ease;
  }
  /* Tooltip — same liquid-glass material as the icon, sits above it. */
  .v2-bd-col-link > span {
    position: absolute;
    left: 50%;
    bottom: calc(100% + 9px);
    transform: translateX(-50%) translateY(3px);
    padding: 5px 10px;
    background: var(--glass-substrate);
    backdrop-filter: blur(40px) saturate(180%);
    -webkit-backdrop-filter: blur(40px) saturate(180%);
    border: 1px solid var(--border, var(--rule, rgba(255, 255, 255, 0.10)));
    border-radius: 8px;
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 9.5px;
    letter-spacing: 0.6px;
    text-transform: uppercase;
    color: var(--txt, var(--txt-pure));
    font-weight: 700;
    white-space: nowrap;
    opacity: 0;
    pointer-events: none;
    box-shadow: var(--shadow-float, 0 10px 26px rgba(0, 0, 0, 0.4));
    transition:
      opacity 180ms cubic-bezier(0.2, 0.8, 0.2, 1),
      transform 180ms cubic-bezier(0.2, 0.8, 0.2, 1);
  }
  /* Tooltip arrow — sits flush under the pill, matches glass border. */
  .v2-bd-col-link > span::after {
    content: '';
    position: absolute;
    top: 100%;
    left: 50%;
    transform: translateX(-50%);
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 4px solid var(--border, var(--rule, rgba(255, 255, 255, 0.10)));
  }
  .v2-bd-col-link svg {
    width: 14px;
    height: 14px;
    transition: transform 200ms cubic-bezier(0.2, 0.8, 0.2, 1);
  }
  .v2-bd-col:hover .v2-bd-col-link,
  .v2-bd-col-link:focus-visible {
    opacity: 1;
    transform: translateX(-50%) translateY(0) scale(1);
    pointer-events: auto;
  }
  .v2-bd-col-link:hover {
    background: rgba(255, 255, 255, 0.12);
    border-color: rgba(255, 255, 255, 0.24);
  }
  .v2-bd-col-link:hover > span,
  .v2-bd-col-link:focus-visible > span {
    opacity: 1;
    transform: translateX(-50%) translateY(0);
  }
  .v2-bd-col-link:hover svg { transform: scale(1.08); }
  @media (prefers-reduced-motion: reduce) {
    .v2-bd-col-link {
      transition: opacity 120ms linear;
      transform: translateX(-50%);
    }
    .v2-bd-col:hover .v2-bd-col-link,
    .v2-bd-col-link:focus-visible { transform: translateX(-50%); }
    .v2-bd-col-link svg, .v2-bd-col-link:hover svg { transform: none; }
    .v2-bd-col-link > span { transition: opacity 120ms linear; transform: translateX(-50%); }
    .v2-bd-col-link:hover > span,
    .v2-bd-col-link:focus-visible > span { transform: translateX(-50%); }
  }

  /* ── DECISIONS column ── */
  .v2-bd-stack {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .v2-bd-dec {
    position: relative;
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 10px 12px 10px 14px;
    border-radius: 8px;
    background: rgba(var(--signature-rgb), 0.025);
    border: 1px solid var(--rule);
    text-decoration: none;
    color: inherit;
    transition: background 200ms ease, border-color 200ms ease, transform 240ms cubic-bezier(0.2, 0.8, 0.2, 1);
    overflow: hidden;
  }
  .v2-bd-dec::before {
    content: '';
    position: absolute;
    left: 0; top: 8px; bottom: 8px;
    width: 2px;
    border-radius: 2px;
  }
  .v2-bd-dec[data-sev='crit']::before { background: var(--danger, #dc2626); box-shadow: 0 0 6px rgba(220, 38, 38, 0.45); }
  .v2-bd-dec[data-sev='warn']::before { background: var(--warning, #d97706); }
  .v2-bd-dec[data-sev='info']::before { background: var(--signature); }
  .v2-bd-dec:hover {
    background: rgba(var(--signature-rgb), 0.06);
    border-color: rgba(var(--signature-rgb), 0.25);
    transform: translateX(2px);
  }
  .v2-bd-dec:hover .v2-bd-dec-arrow {
    opacity: 1;
    transform: translateX(0);
  }
  .v2-bd-dec-head {
    display: flex;
    align-items: baseline;
    gap: 8px;
  }
  .v2-bd-dec-count {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 14px;
    font-weight: 700;
    font-variant-numeric: tabular-nums;
    letter-spacing: -0.025em;
    line-height: 1;
  }
  .v2-bd-dec[data-sev='crit'] .v2-bd-dec-count { color: var(--danger, #dc2626); }
  .v2-bd-dec[data-sev='warn'] .v2-bd-dec-count { color: var(--warning, #d97706); }
  .v2-bd-dec[data-sev='info'] .v2-bd-dec-count { color: var(--signature); }
  .v2-bd-dec-label {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    letter-spacing: 0.6px;
    text-transform: uppercase;
    color: var(--txt-faint);
    font-weight: 600;
    flex: 1;
  }
  .v2-bd-dec-arrow {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 12px;
    color: var(--txt-faint);
    opacity: 0;
    transform: translateX(-4px);
    transition: opacity 200ms ease, transform 200ms ease;
  }
  .v2-bd-dec-top {
    padding-left: 0;
  }
  .v2-bd-dec-text {
    font-size: 12px;
    line-height: 1.4;
    color: var(--txt-pure);
    letter-spacing: -0.005em;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
  }
  .v2-bd-dec-project {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10.5px;
    color: var(--txt-faint);
  }

  /* ── UPDATES column — git commit feed ── */
  .v2-bd-updates {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .v2-bd-update-link {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    padding: 8px 10px;
    border-radius: 7px;
    text-decoration: none;
    color: inherit;
    transition: background 200ms ease, transform 240ms cubic-bezier(0.2, 0.8, 0.2, 1);
    position: relative;
  }
  .v2-bd-update-link:hover {
    background: rgba(var(--signature-rgb), 0.07);
    transform: translateX(2px);
  }
  .v2-bd-update-link:hover .v2-bd-update-arrow {
    opacity: 1;
    transform: translateX(0);
  }
  .v2-bd-update-sha {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.3px;
    color: var(--signature);
    background: rgba(var(--signature-rgb), 0.1);
    padding: 3px 6px;
    border-radius: 4px;
    flex-shrink: 0;
    margin-top: 1px;
    border: 1px solid rgba(var(--signature-rgb), 0.22);
  }
  .v2-bd-update-body {
    display: flex;
    flex-direction: column;
    gap: 3px;
    min-width: 0;
    flex: 1;
  }
  .v2-bd-update-text {
    font-size: 12.5px;
    line-height: 1.4;
    color: var(--txt-pure);
    letter-spacing: -0.005em;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    font-weight: 500;
  }
  .v2-bd-update-meta {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 9.5px;
    letter-spacing: 0.4px;
    color: var(--txt-faint);
    flex-wrap: wrap;
  }
  .v2-bd-update-project {
    color: var(--signature);
    text-transform: uppercase;
    font-weight: 700;
    opacity: 0.9;
  }
  .v2-bd-update-author {
    color: var(--txt-muted);
    font-weight: 500;
  }
  .v2-bd-update-time {
    color: var(--txt-faint);
    font-weight: 500;
  }
  .v2-bd-update-sep {
    opacity: 0.4;
  }
  .v2-fc-pending,
  .v2-bd-update-pending {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 9px;
    letter-spacing: 0.6px;
    text-transform: uppercase;
    color: var(--signature);
    font-weight: 700;
    opacity: 0.85;
  }
  .v2-bd-update-pending-dot {
    width: 5px; height: 5px;
    border-radius: 50%;
    background: currentColor;
    box-shadow: 0 0 5px currentColor;
    animation: v2bdUpdatePulse 1.4s ease-in-out infinite;
  }
  @keyframes v2bdUpdatePulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50%      { opacity: 0.4; transform: scale(1.3); }
  }
  .v2-bd-update-link[data-summarizing='true'] .v2-bd-update-text {
    color: var(--txt-muted);
    font-style: italic;
  }
  .v2-bd-update-arrow {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 13px;
    color: var(--success, #059669);
    opacity: 0;
    transform: translateX(-4px);
    transition: opacity 200ms ease, transform 200ms ease;
    align-self: center;
    flex-shrink: 0;
  }

  /* ── TEAM HEALTH column — load distribution + velocity foot ── */
  .v2-bd-loads {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .v2-bd-load {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 4px 0;
  }
  .v2-bd-load-glyph {
    width: 22px; height: 22px;
    border-radius: 50%;
    flex-shrink: 0;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    font-weight: 700;
    color: white;
    background: var(--txt-faint);
    text-transform: uppercase;
    box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.06);
  }
  .v2-bd-load-glyph[data-has-image='true'] {
    background: transparent;
    color: transparent;
    overflow: hidden;
    padding: 0;
  }
  .v2-bd-load-glyph-img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
    border-radius: inherit;
  }
  .v2-bd-load-glyph[data-idle='true'] {
    opacity: 0.55;
  }
  .v2-bd-load-body {
    display: flex;
    flex-direction: column;
    gap: 5px;
    min-width: 0;
    flex: 1;
  }
  .v2-bd-load-head {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 8px;
  }
  .v2-bd-load-name {
    font-size: 12.5px;
    font-weight: 600;
    color: var(--txt-pure);
    letter-spacing: -0.005em;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    min-width: 0;
  }
  .v2-bd-load-pct {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    font-variant-numeric: tabular-nums;
    font-weight: 700;
    letter-spacing: -0.005em;
    flex-shrink: 0;
    color: var(--txt-faint);
  }
  .v2-bd-load-pct[data-load='high'] { color: var(--danger, #dc2626); }
  .v2-bd-load-pct[data-load='med']  { color: var(--warning, #d97706); }
  .v2-bd-load-pct[data-load='low']  { color: var(--success, #059669); }
  .v2-bd-load-pct[data-load='idle'] { color: var(--txt-faint); opacity: 0.7; text-transform: uppercase; }
  .v2-bd-load-bar-track {
    display: block;
    height: 4px;
    background: rgba(var(--signature-rgb), 0.06);
    border-radius: 2px;
    overflow: hidden;
    border: 1px solid rgba(var(--signature-rgb), 0.05);
  }
  .v2-bd-load-bar-fill {
    display: block;
    height: 100%;
    border-radius: 2px;
    transition: width 600ms cubic-bezier(0.2, 0.8, 0.2, 1);
    background: var(--success, #059669);
  }
  .v2-bd-load-bar-fill[data-load='high'] {
    background: linear-gradient(90deg, var(--danger, #dc2626), rgba(220, 38, 38, 0.8));
    box-shadow: 0 0 4px rgba(220, 38, 38, 0.4);
  }
  .v2-bd-load-bar-fill[data-load='med'] {
    background: linear-gradient(90deg, var(--warning, #d97706), rgba(217, 119, 6, 0.8));
  }
  .v2-bd-load-foot {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 10px 0 0;
    border-top: 1px solid rgba(var(--signature-rgb), 0.08);
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-size: 10px;
    letter-spacing: 0.3px;
    color: var(--txt-faint);
    flex-wrap: wrap;
  }
  .v2-bd-load-foot-cell {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    text-transform: uppercase;
    font-weight: 600;
  }
  .v2-bd-load-trend {
    font-weight: 700;
    color: var(--txt-pure);
  }
  .v2-bd-load-trend[data-trend='up']   { color: var(--success, #059669); }
  .v2-bd-load-trend[data-trend='down'] { color: var(--danger, #dc2626); }
  .v2-bd-load-trend[data-trend='flat'] { color: var(--txt-faint); }
  /* ── All-clear ── */
  .v2-bd-clear {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    padding: 4px 0;
    font-size: 12px;
    color: var(--txt-muted);
    line-height: 1.45;
  }
  .v2-bd-clear-glyph {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 18px; height: 18px;
    border-radius: 50%;
    background: rgba(16, 185, 129, 0.12);
    color: var(--success, #059669);
    flex-shrink: 0;
    margin-top: 1px;
    box-shadow: 0 0 0 1px rgba(16, 185, 129, 0.25);
  }

  /* ── Skeleton ── */
  .v2-bd-skel { display: flex; flex-direction: column; gap: 8px; padding: 4px 0; }
  .v2-bd-skel-line {
    height: 12px;
    background: rgba(var(--signature-rgb), 0.05);
    border-radius: 4px;
    animation: v2bdSkel 1.6s ease-in-out infinite;
  }
  .v2-bd-skel-l { width: 80%; }
  .v2-bd-skel-m { width: 60%; }
  .v2-bd-skel-s { width: 40%; }
  @keyframes v2bdSkel {
    0%, 100% { opacity: 0.45; }
    50%      { opacity: 0.85; }
  }
`;
